SET SERVEROUTPUT ON
DECLARE
  V_CNT  NUMBER := 1;
  V_STR  VARCHAR2(10) := NULL;
BEGIN
  WHILE V_CNT <= 5 LOOP
    V_STR := V_STR || '*';
    DBMS_OUTPUT.PUT_LINE(V_STR);
    V_CNT := V_CNT + 1;
  END LOOP;
END;
/
