CREATE OR REPLACE FUNCTION SEL_EMPNAME02(
       VENAME IN EMP.ENAME%TYPE)
  RETURN VARCHAR
IS
  VJOB EMP.JOB%TYPE;
BEGIN
  SELECT JOB INTO VJOB
  FROM EMP
  WHERE ENAME=VENAME;
  
  RETURN VJOB;
END;
/