SET SERVEROUTPUT ON
CREATE OR REPLACE PROCEDURE SEL_EMP(
   VDEPTNO IN EMP.DEPTNO%TYPE )
IS
   VEMP EMP%ROWTYPE;

   CURSOR C1 
   IS
   SELECT * FROM EMP
   WHERE DEPTNO=VDEPTNO; 
BEGIN
   DBMS_OUTPUT.PUT_LINE('사원번호 / 사원명 / 직급 / 급여'); 
   DBMS_OUTPUT.PUT_LINE('--------------------------------');
   FOR VEMP IN C1 LOOP
      EXIT WHEN C1%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE(VEMP.EMPNO||
            '  '||VEMP.ENAME||'  '||VEMP.JOB||'  '||VEMP.SAL);   
   END LOOP;
END;
/

